/**
 * worker.js — Orchestrator Web Worker
 *
 * Hosts ONNX Runtime Web (WebGPU EP) and the Rust Wasm core.
 * Handles two message types:
 *   • MODE_TRAIN  – run the full pipeline on 1-5 training images and return a
 *                   128-d mean face embedding.
 *   • MODE_MATCH  – run detection + recognition on a page image and return
 *                   matching bounding boxes.
 */

import * as ort from "./vendor/onnxruntime-web/ort.webgpu.min.mjs";

// ── Wasm core ─────────────────────────────────────────────────────────────────
// Import the wasm-bindgen JS glue (generated by `wasm-pack build --target web`)
import init, {
  apply_nms,
  crop_and_normalize_batch,
  euclidean_distance,
  calculate_mean_vector,
} from "./wasm-core/pkg/seashells_wasm.js";

// ── Configuration ─────────────────────────────────────────────────────────────
const DETECTION_MODEL_PATH  = chrome.runtime.getURL("models/ultraface_320.onnx");
const RECOGNITION_MODEL_PATH = chrome.runtime.getURL("models/mobilefacenet.onnx");
const DETECTION_SIZE = 320; // ultraface_320 input width/height
const EMBED_DIM      = 128; // MobileFaceNet embedding dimension

// Tuning knobs (can be overridden per message)
const CONF_THRESHOLD_DEFAULT = 0.7;
const NMS_IOU_THRESHOLD      = 0.4;

// ── Lazy-initialised state ────────────────────────────────────────────────────
let wasmReady   = false;
let detSession  = null;
let recSession  = null;

// ── Bootstrap ────────────────────────────────────────────────────────────────
async function bootstrap() {
  // 1. Init Rust Wasm
  await init(chrome.runtime.getURL("wasm-core/pkg/seashells_wasm_bg.wasm"));
  wasmReady = true;

  // 2. Init ONNX sessions (prefer WebGPU, fall back to wasm)
  const epList = ["webgpu", "wasm"];
  const sessionOptions = { executionProviders: epList };

  [detSession, recSession] = await Promise.all([
    ort.InferenceSession.create(DETECTION_MODEL_PATH, sessionOptions),
    ort.InferenceSession.create(RECOGNITION_MODEL_PATH, sessionOptions),
  ]);
}

const readyPromise = bootstrap().catch((err) => {
  console.error("[Seashells worker] bootstrap failed:", err);
});

// ── Message handler ───────────────────────────────────────────────────────────
self.onmessage = async (event) => {
  const { type, id, payload } = event.data;

  try {
    await readyPromise;
    if (!wasmReady || !detSession || !recSession) {
      throw new Error("Worker not ready yet");
    }

    if (type === "MODE_TRAIN") {
      const result = await handleTrain(payload);
      self.postMessage({ id, type: "TRAIN_RESULT", payload: result }, [
        result.meanVector.buffer,
      ]);
    } else if (type === "MODE_MATCH") {
      const result = await handleMatch(payload);
      // boxes is a plain JS array; no transferable needed
      self.postMessage({ id, type: "MATCH_RESULT", payload: result });
    } else {
      throw new Error(`Unknown message type: ${type}`);
    }
  } catch (err) {
    self.postMessage({ id, type: "ERROR", payload: { message: err.message } });
  }
};

// ── Training pipeline ─────────────────────────────────────────────────────────
/**
 * payload:
 *   images: Array of { buffer: ArrayBuffer, width: number, height: number }
 *
 * Returns: { meanVector: Float32Array }
 */
async function handleTrain({ images }) {
  const allEmbeddings = []; // will collect Float32Array(128) per face

  for (const imgData of images) {
    const { buffer, width, height } = imgData;
    const rgba = new Uint8Array(buffer);

    // Detection
    const boxes = await runDetection(rgba, width, height);
    if (boxes.length === 0) continue;

    // Crop + normalise via Rust
    const bboxFlat = new Float32Array(
      boxes.flatMap((b) => [b.x1, b.y1, b.x2, b.y2])
    );
    const u8view  = new Uint8Array(rgba);
    // wasm expects Uint8Array
    const batched = crop_and_normalize_batch(u8view, width, height, bboxFlat);

    // Recognition – use only the first (best-scoring) face from each image
    const embedding = await runRecognition(batched.slice(0, 3 * 112 * 112), 1);
    allEmbeddings.push(...embedding); // embedding is Float32Array(128)
  }

  if (allEmbeddings.length === 0) {
    throw new Error("No faces detected in training images");
  }

  // Pack embeddings into flat array and compute mean via Rust
  const flat = new Float32Array(allEmbeddings.length * EMBED_DIM);
  allEmbeddings.forEach((emb, i) =>
    flat.set(emb, i * EMBED_DIM)
  );
  const meanVector = calculate_mean_vector(flat, EMBED_DIM);
  return { meanVector };
}

// ── Matching pipeline ─────────────────────────────────────────────────────────
/**
 * payload:
 *   buffer:        ArrayBuffer – RGBA pixel data of the page image
 *   width:         number
 *   height:        number
 *   targetVector:  Float32Array(128) – the stored mean embedding
 *   threshold:     number            – distance threshold (e.g. 1.2)
 *
 * Returns: { boxes: Array<{x1,y1,x2,y2}> }
 */
async function handleMatch({ buffer, width, height, targetVector, threshold }) {
  const rgba = new Uint8Array(buffer);

  // Detection
  const boxes = await runDetection(rgba, width, height);
  if (boxes.length === 0) return { boxes: [] };

  // Crop + normalise batch via Rust
  const bboxFlat = new Float32Array(
    boxes.flatMap((b) => [b.x1, b.y1, b.x2, b.y2])
  );
  const u8view  = new Uint8Array(rgba);
  const batched = crop_and_normalize_batch(
    u8view, width, height, bboxFlat
  );

  // Recognition for all faces in one batch
  const embeddings = await runRecognition(batched, boxes.length);
  const target     = new Float32Array(targetVector);

  // Filter by distance
  const matchingBoxes = [];
  for (let i = 0; i < boxes.length; i++) {
    const emb  = embeddings[i];
    const dist = euclidean_distance(emb, target);
    if (dist <= threshold) {
      matchingBoxes.push(boxes[i]);
    }
  }

  return { boxes: matchingBoxes };
}

// ── Detection helper ──────────────────────────────────────────────────────────
/**
 * Runs ultraface_320 on the given RGBA buffer.
 * Returns an array of { x1, y1, x2, y2 } in *pixel* coordinates.
 */
async function runDetection(rgba, imgWidth, imgHeight) {
  // Pre-process: resize to 320×240 (ultraface aspect) and normalise
  const inputH = 240, inputW = DETECTION_SIZE;
  const tensor = rgbaToDetectionTensor(rgba, imgWidth, imgHeight, inputW, inputH);

  const feeds = { [detSession.inputNames[0]]: tensor };
  const results = await detSession.run(feeds);

  // ultraface_320 outputs: scores [1, N, 2], boxes [1, N, 4]
  const scoresOut = results[detSession.outputNames[0]].data; // Float32Array
  const boxesOut  = results[detSession.outputNames[1]].data; // Float32Array

  const numPriors = scoresOut.length / 2;

  // Collect confident face detections
  const rawBoxes   = [];
  const rawScores  = [];

  for (let i = 0; i < numPriors; i++) {
    const faceScore = scoresOut[i * 2 + 1]; // class 1 = face
    if (faceScore < CONF_THRESHOLD_DEFAULT) continue;

    // Model outputs normalised [cx, cy, w, h] – convert to x1y1x2y2 pixels
    const cx = boxesOut[i * 4]     * imgWidth;
    const cy = boxesOut[i * 4 + 1] * imgHeight;
    const bw = boxesOut[i * 4 + 2] * imgWidth;
    const bh = boxesOut[i * 4 + 3] * imgHeight;

    rawBoxes.push(cx - bw / 2, cy - bh / 2, cx + bw / 2, cy + bh / 2);
    rawScores.push(faceScore);
  }

  if (rawBoxes.length === 0) return [];

  // NMS via Rust
  const boxesArr  = new Float32Array(rawBoxes);
  const scoresArr = new Float32Array(rawScores);
  const keptIdx   = apply_nms(boxesArr, scoresArr, NMS_IOU_THRESHOLD);

  const boxes = [];
  for (let k = 0; k < keptIdx.length; k++) {
    const i = keptIdx[k];
    boxes.push({
      x1: rawBoxes[i * 4],
      y1: rawBoxes[i * 4 + 1],
      x2: rawBoxes[i * 4 + 2],
      y2: rawBoxes[i * 4 + 3],
    });
  }
  return boxes;
}

/**
 * Convert RGBA Uint8Array → ONNX float tensor [1, 3, H, W] for detection.
 * Pixels are normalised to [−1, 1] as expected by UltraFace.
 */
function rgbaToDetectionTensor(rgba, srcW, srcH, dstW, dstH) {
  const floats = new Float32Array(3 * dstH * dstW);
  for (let dy = 0; dy < dstH; dy++) {
    for (let dx = 0; dx < dstW; dx++) {
      const sx = Math.floor((dx + 0.5) * srcW / dstW);
      const sy = Math.floor((dy + 0.5) * srcH / dstH);
      const si = (sy * srcW + sx) * 4;
      const di = dy * dstW + dx;
      floats[di]             = (rgba[si]     / 127.5) - 1; // R
      floats[dstH * dstW + di]     = (rgba[si + 1] / 127.5) - 1; // G
      floats[2 * dstH * dstW + di] = (rgba[si + 2] / 127.5) - 1; // B
    }
  }
  return new ort.Tensor("float32", floats, [1, 3, dstH, dstW]);
}

// ── Recognition helper ────────────────────────────────────────────────────────
/**
 * Runs MobileFaceNet on a pre-cropped batch of face tensors.
 * `batchData` is Float32Array of shape [N, 3, 112, 112].
 * Returns an array of N Float32Array(128) embeddings.
 */
async function runRecognition(batchData, n) {
  const tensor = new ort.Tensor("float32", batchData, [n, 3, 112, 112]);
  const feeds  = { [recSession.inputNames[0]]: tensor };
  const results = await recSession.run(feeds);
  const raw     = results[recSession.outputNames[0]].data; // Float32Array [N*128]

  const embeddings = [];
  for (let i = 0; i < n; i++) {
    embeddings.push(raw.slice(i * EMBED_DIM, (i + 1) * EMBED_DIM));
  }
  return embeddings;
}
